name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 9:21
    - cron: '21 9 * * *'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.0

  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y libenchant-2-dev
        if: runner.os == 'Linux'
      - name: Install dependencies
        run: brew install enchant
        if: runner.os == 'macOS'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up nox
        uses: wntrblm/nox@2022.8.7
      - name: Install libavif
        run: >
          curl -L 'https://github.com/AOMediaCodec/libavif/archive/v0.11.1.tar.gz' | tar xzf - &&
          cd libavif* &&
          mkdir build && cd build &&
          cmake .. &&
          make -j $(($(nproc) + 1)) &&
          sudo make install
      - name: Add /usr/local/lib to LD_LIBRARY_PATH
        run: echo 'LD_LIBRARY_PATH=/usr/local/lib' >> $GITHUB_ENV
      - name: Run nox
        run: nox

  packaging:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: python -m pip install build
      - name: Create packages
        run: python -m build .
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
      - name: Create a Release
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          generate_release_notes: true
