name: Coverage

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Ensure we have new enough versions to respect python_version
      run: python -m pip install -U pip setuptools
    - name: Install tox
      run: python -m pip install tox
    - name: Install dependencies
      run: >
        curl -L 'https://github.com/AOMediaCodec/libavif/archive/v0.8.4.tar.gz' | tar xzf - &&
        cd libavif* &&
        mkdir build && cd build &&
        cmake .. &&
        make -j $(($(nproc) + 1)) &&
        sudo make install
    - name: Add /usr/local/lib to LD_LIBRARY_PATH
      run: echo 'LD_LIBRARY_PATH=/usr/local/lib' >> $GITHUB_ENV
      if: runner.os == 'Linux'
    - name: Collect & Upload Coverage
      run: python -m tox -e py39-codecov
      env:
        CODECOV_TOKEN: dc421f3f-223f-4c28-8be8-2c265033e42b
